[tool.black]
line-length = 160

[tool.ruff]
line-length = 160

[tool.poetry]
name = "azure-kusto-python"
version = "4.1.2"
description = ""
authors = ["AsafMah <asafmahlev@microsoft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
mock = "^5.0.1"
responses = "^0.22.0"
black = "^23.1.0"
aioresponses = "^0.7.4"
pytest-asyncio = "^0.20.3"
azure-storage-blob = "^12.15.0"
pandas = "~1.3.0"
asgiref = "^3.6.0"
poethepoet = "^0.18.1"
ruff = "^0.0.252"


[tool.poe.tasks]
black = "black ."
black-check = "black --check ."
ruff = "ruff --check ."
ruff-fix = "ruff --fix ."
pyright = "pyright"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
