name: PyPi Release Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Publish azure-kusto-data
      working-directory: ./azure-kusto-data
      env:
        TWINE_USERNAME: microsoftkusto
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Publish azure-kusto-ingest
      working-directory: ./azure-kusto-ingest
      env:
        TWINE_USERNAME: microsoftkusto
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
